name: Release CD

on:
  push:
    branches:
      - release
    tags-ignore:
      - '*'
  
  pull_request:
    branches:
      - release
    types:
      - closed

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Create variable
      run: |
        echo "tag_name=v$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
      
    - name: Install
      run: npm ci

    - name: Build  
      run: npm run esprod

    - name: Zip dist
      run: cd dist && zip -r ../page-tweeter_${{ env.tag_name }}.zip *

    - name: Release
      run: |
        gh release create ${{ env.tag_name }} --generate-notes page-tweeter_${{ env.tag_name }}.zip
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      